// Phase-0 measurement: apply every catalog mutation to every anchor on the
// fixture page, classify the delta, and compare against the known label.
// Also classifies any committed live pairs from spikes/live-pairs/.
import { writeFile, readdir, readFile } from 'node:fs/promises';
import { chromium } from 'playwright';
import { startFixtureServer } from '../test/helpers/serve.js';
import { serializeDom } from '../src/probe/serialize.js';
import { cosmeticMutations } from '../src/probe/catalogs/cosmetic.js';
import { semanticMutations } from '../src/probe/catalogs/semantic.js';
import { classifyDelta } from '../src/triage/classify.js';

// Note: Playwright-only pseudo-selectors (:text-is etc.) are not resolvable
// via document.querySelector, so serializeDom cannot anchor on them in
// phase 0. The text-selector classification path is covered by unit tests
// in test/classify.test.js instead.
const ANCHORS = [
  '#cta',                             // robust id selector
  'header > a.btn',                   // structural + class
  '#main-nav > li:nth-child(2) > a',  // deeply structural
  'li.css-1a2b3c',                    // relies on a hashed class
];

const catalogs = [
  ['cosmetic', cosmeticMutations],
  ['semantic', semanticMutations],
];

const rows = [];
const skipped = [];

const server = await startFixtureServer();
const browser = await chromium.launch();

for (const [label, catalog] of catalogs) {
  for (const mutation of catalog) {
    for (const selector of ANCHORS) {
      const page = await browser.newPage();
      await page.goto(server.url);
      const baseline = await page.evaluate(serializeDom, selector);
      if (!baseline.anchorPath) {
        skipped.push({ mutationId: mutation.id, selector, why: 'anchor not on page' });
        await page.close();
        continue;
      }
      // Mutate the anchor element itself.
      const applied = await page.evaluate(mutation.apply, selector);
      if (!applied) {
        skipped.push({ mutationId: mutation.id, selector, why: 'mutation not applicable' });
        await page.close();
        continue;
      }
      const current = await page.evaluate(serializeDom, null);
      const { verdict, reasons } = classifyDelta(baseline, current, selector);
      rows.push({ source: 'fixture', label, mutationId: mutation.id, selector, verdict, reasons });
      await page.close();
    }
  }
}

await browser.close();
await server.close();

// Committed live pairs (created manually via spikes/capture-live.js).
try {
  for (const file of await readdir(new URL('./live-pairs/', import.meta.url))) {
    if (file.startsWith('_')) continue;
    if (!file.endsWith('.json')) continue;
    const pair = JSON.parse(await readFile(new URL(`./live-pairs/${file}`, import.meta.url), 'utf8'));
    const { verdict, reasons } = classifyDelta(pair.baseline, pair.current, pair.selector);
    rows.push({ source: 'live', label: pair.label, mutationId: pair.mutationId, selector: pair.selector, verdict, reasons });
  }
} catch { /* no live pairs yet */ }

try {
  const liveSkips = JSON.parse(
    await readFile(new URL('./live-pairs/_skips.json', import.meta.url), 'utf8'),
  );
  skipped.push(...liveSkips);
} catch { /* no live skips recorded */ }

const misclassified = rows.filter(
  (r) => (r.label === 'cosmetic' && r.verdict === 'semantic')
      || (r.label === 'semantic' && r.verdict === 'cosmetic'),
);
const unclear = rows.filter((r) => r.verdict === 'unclear');
const count = (label, verdict) => rows.filter((r) => r.label === label && r.verdict === verdict).length;

const report = `# flakeproof phase 0 report

Generated by \`spikes/run-phase0.js\`.

## Confusion matrix

| label \\ verdict | cosmetic | semantic | unclear |
|---|---|---|---|
| cosmetic | ${count('cosmetic', 'cosmetic')} | ${count('cosmetic', 'semantic')} | ${count('cosmetic', 'unclear')} |
| semantic | ${count('semantic', 'cosmetic')} | ${count('semantic', 'semantic')} | ${count('semantic', 'unclear')} |

Total cases: ${rows.length} (live: ${rows.filter((r) => r.source === 'live').length}), skipped: ${skipped.length}

## Misclassifications (success criterion: 0)

${misclassified.length === 0 ? 'None.' : misclassified.map((r) => `- ${r.mutationId} at \`${r.selector}\` judged ${r.verdict}: ${r.reasons.join('; ')}`).join('\n')}

## Unclear cases

${unclear.length === 0 ? 'None.' : unclear.map((r) => `- ${r.mutationId} at \`${r.selector}\` (${r.label}): ${r.reasons.join('; ') || 'no signals'}`).join('\n')}

## Skipped

${skipped.length === 0 ? 'None.' : skipped.map((s) => `- ${s.mutationId} at \`${s.selector}\`: ${s.why}`).join('\n')}
`;

await writeFile(new URL('./phase0-report.md', import.meta.url), report, 'utf8');
console.log(report);
process.exit(misclassified.length > 0 ? 1 : 0);
